services:
    mongodb:
        image: mongo:8.0.4
        container_name: product_mongodb
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: changeinprod
            MONGO_INITDB_DATABASE: product_service
        volumes:
            - mongodb_product_data:/data/db

volumes:
    mongodb_product_data:
